services:
  - type: web
    name: smart-sprinkler
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TIDB_HOST
        sync: false
      - key: TIDB_PORT
        value: 4000
      - key: TIDB_USER
        sync: false
      - key: TIDB_PASSWORD
        sync: false
      - key: TIDB_DATABASE
        value: smart_sprinkler
